/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revolut.live.coding;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        //given
        App sut = new App();

        // when
        String greeting = sut.getGreeting();

        // then
        assertNotNull(greeting, "app should have a greeting");
    }

    @Test
    void should() {
    // given
    // when
    App.main(new String[]{"test"});

    // then
    }
}
